# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhaSetTimeoutMinutes < Formula
  desc "Set timeout-minutes to GitHub Actions jobs
"
  homepage "https://github.com/suzuki-shunsuke/gha-set-timeout-minutes"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/gha-set-timeout-minutes/releases/download/v0.1.0/gha-set-timeout-minutes_darwin_amd64.tar.gz"
      sha256 "bba75e5f6fc7da2631cfc220aa0cc10bf9d6792c0c9ddb3ef516745b13177ad6"

      def install
        bin.install "gha-set-timeout-minutes"
        generate_completions_from_executable(bin/"gha-set-timeout-minutes", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/gha-set-timeout-minutes/releases/download/v0.1.0/gha-set-timeout-minutes_darwin_arm64.tar.gz"
      sha256 "db91b4fac77036171adf495cbcdfe5c1ed33374c499aa2664bb8649f0f557f22"

      def install
        bin.install "gha-set-timeout-minutes"
        generate_completions_from_executable(bin/"gha-set-timeout-minutes", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/gha-set-timeout-minutes/releases/download/v0.1.0/gha-set-timeout-minutes_linux_amd64.tar.gz"
        sha256 "c81cab9813d592ac5c947470867c1989d6b860bc5af6e63088b913fa42cccc0c"

        def install
          bin.install "gha-set-timeout-minutes"
          generate_completions_from_executable(bin/"gha-set-timeout-minutes", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/gha-set-timeout-minutes/releases/download/v0.1.0/gha-set-timeout-minutes_linux_arm64.tar.gz"
        sha256 "8ec4fce9f97d62af9cc2ded2fe4f0031d2557bbd787a60d2dc887ce1c6c59843"

        def install
          bin.install "gha-set-timeout-minutes"
          generate_completions_from_executable(bin/"gha-set-timeout-minutes", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/gha-set-timeout-minutes --version"
  end
end
