# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghatm < Formula
  desc "Set timeout-minutes to GitHub Actions jobs
"
  homepage "https://github.com/suzuki-shunsuke/ghatm"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.0/ghatm_darwin_amd64.tar.gz"
      sha256 "95a0d3db38d82fcf9af5c31c8623e6bc802a39aec718df840ad9e89eab07b8ba"

      def install
        bin.install "ghatm"
        generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.0/ghatm_darwin_arm64.tar.gz"
      sha256 "fde57ab849ae4576c0ae333ee6ff0aefd7d42dc12035dd87b783090bdb5e361a"

      def install
        bin.install "ghatm"
        generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.0/ghatm_linux_amd64.tar.gz"
        sha256 "86035a92bfea60b9027c68ba7c7793bc627b599d29e815d24413a5ccfa86bab3"

        def install
          bin.install "ghatm"
          generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.0/ghatm_linux_arm64.tar.gz"
        sha256 "b0aca21705b8a1f686a9a5b1d9316b6bc73c7faeda3831d713abf93f964bcbea"

        def install
          bin.install "ghatm"
          generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghatm --version"
  end
end
