# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghatm < Formula
  desc "Set timeout-minutes to GitHub Actions jobs
"
  homepage "https://github.com/suzuki-shunsuke/ghatm"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.4/ghatm_darwin_amd64.tar.gz"
      sha256 "53b50cffefeb3439b47889ee629539a04d67f5d9e1dd39a25a1c95f2c5f90c03"

      def install
        bin.install "ghatm"
        generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.4/ghatm_darwin_arm64.tar.gz"
      sha256 "1d1d37b4b8362b83ce5d15d2eeebfda175474525c2913d86b2ac6249926ef8ea"

      def install
        bin.install "ghatm"
        generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.4/ghatm_linux_amd64.tar.gz"
        sha256 "8724d5946f5f62defa01d17b5651629eb9ff47963f0d2114dd2da30c0bad7205"

        def install
          bin.install "ghatm"
          generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.4/ghatm_linux_arm64.tar.gz"
        sha256 "3fc349cc468371ccc9bb8d032707bb8a1989ed89bcf9f87322c1a94279c9fb5f"

        def install
          bin.install "ghatm"
          generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghatm --version"
  end
end
