# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghatm < Formula
  desc "Set timeout-minutes to GitHub Actions jobs
"
  homepage "https://github.com/suzuki-shunsuke/ghatm"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.5/ghatm_darwin_amd64.tar.gz"
      sha256 "51659699051ffa181bcd63ec513aeea1d7f8ea937448751268327179e62564b0"

      def install
        bin.install "ghatm"
        generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.5/ghatm_darwin_arm64.tar.gz"
      sha256 "c91a64f4c119857ddb56f8a8238a9ea351171df02c4e32d3f5a4426251ca164b"

      def install
        bin.install "ghatm"
        generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.5/ghatm_linux_amd64.tar.gz"
        sha256 "d3c5ef13a7947adca97f5a0d3caf3cfd7e06e3ec6e3c7b3fd43ddb10e2f1f6cd"

        def install
          bin.install "ghatm"
          generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.5/ghatm_linux_arm64.tar.gz"
        sha256 "1e9e25f94b2affca52b08a745cb5a5c3fec5400585e0d84435b665f510e0f68a"

        def install
          bin.install "ghatm"
          generate_completions_from_executable(bin/"ghatm", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghatm --version"
  end
end
