# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghatm" do
  desc "Set timeout-minutes to GitHub Actions jobs
"
  homepage "https://github.com/suzuki-shunsuke/ghatm"
  version "0.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghatm"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.6/ghatm_darwin_amd64.tar.gz"
      sha256 "b01568214d5d5e7ab5abd34237ca17989e84d05f27fb3e22683987b3a58d5b4b"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.6/ghatm_darwin_arm64.tar.gz"
      sha256 "1449b5cd5c639d9e8267787a57acaab9a3cef0844d938cdd74430b6b0cf26cf4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.6/ghatm_linux_amd64.tar.gz"
      sha256 "579070b81b0e2ee3ef4579cabc8f79c7a917610c2b4fdbb0c31ee8b7d5887179"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v0.3.6/ghatm_linux_arm64.tar.gz"
      sha256 "3cefac568bba2f87aaf307fbb0e2f9c547dca974ce217fd8bdf8b7892217bec9"
    end
  end

  # No zap stanza required
end
