# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghatm" do
  name "ghatm"
  desc "Set timeout-minutes to GitHub Actions jobs
"
  homepage "https://github.com/suzuki-shunsuke/ghatm"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghatm"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v#{version}/ghatm_darwin_amd64.tar.gz"
      sha256 "1d9eef823cbc2a7e8789c0a1511896292a831d477670b9b4180a9a9db817ebad"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v#{version}/ghatm_darwin_arm64.tar.gz"
      sha256 "63204eb557d71e8cf5af739a82444cf231581f067e36903aece3e172544d16a8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v#{version}/ghatm_linux_amd64.tar.gz"
      sha256 "22195c41bc439958e3983ad1cf6f7b2d3ed8a0685df4b15bff5b2bbfb38118ed"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghatm/releases/download/v#{version}/ghatm_linux_arm64.tar.gz"
      sha256 "92368685124a3a7db0e59c2c56e9ab1af3eaf636a8f891c86684f5b6010ed5e5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghatm"]
    end
  end

  # No zap stanza required
end
